SELECT  S.USERNAME
         ,DECODE(L.TYPE, 'TM', 'TABLE LOCK', 'TX', 'ROW LOCK', NULL) LOCK_LEVEL
         ,O.OWNER
         ,O.OBJECT_NAME
         ,O.OBJECT_TYPE
         ,S.SID
         ,S.SERIAL#
   FROM GV$SESSION S, GV$LOCK L, DBA_OBJECTS O
  WHERE L.SID = S.SID
    AND L.ID1 = O.OBJECT_ID(+)
    AND S.USERNAME IS NOT NULL
    AND O.OWNER='USERNAME';
   
ALTER SYSTEM KILL SESSION  'SID, SERIAL#';