SELECT  A.TABLESPACE_NAME
        ,A.BYTES / 1024 / 1024 "SUM MB"
        ,(A.BYTES - B.BYTES) / 1024 / 1024 "USED MB"
        ,B.BYTES / 1024 / 1024 "FREE MB"
        ,ROUND(((A.BYTES - B.BYTES) / A.BYTES) * 100, 2) "PERCENT_USED"
  FROM (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES
           FROM DBA_DATA_FILES
          GROUP BY TABLESPACE_NAME) A,
        (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES, MAX(BYTES) LARGEST
           FROM DBA_FREE_SPACE
          GROUP BY TABLESPACE_NAME) B
 WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME
 ORDER BY ((A.BYTES - B.BYTES) / A.BYTES) DESC;